### ISSUE TITLE
The plugin is unable to reinitialize itself when touching the code

### ISSUE THREAD

**Issue by xel1045** [eXolnet/redmine-code-audit#70]
```
LoadError
Unable to autoload constant Project, expected /var/www/redmine/app/models/project.rb to define it

vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:495:in `load_missing_constant'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:184:in `const_missing'
plugins/code_audit/lib/code_audit/patches/project_patch.rb:24:in `<top (required)>'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:457:in `load'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:457:in `block in load_file'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:647:in `new_constants_in'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:456:in `load_file'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:354:in `require_or_load'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:317:in `depend_on'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:233:in `require_dependency'
plugins/code_audit/init.rb:13:in `block in <top (required)>'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:444:in `instance_exec'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:444:in `block in make_lambda'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:190:in `call'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:190:in `block in simple'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `call'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `block in call'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `each'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `call'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
vendor/bundle/ruby/1.9.1/gems/actionpack-4.2.3/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
vendor/bundle/ruby/1.9.1/gems/actionpack-4.2.3/lib/action_dispatch/middleware/reloader.rb:71:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
vendor/bundle/ruby/1.9.1/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
vendor/bundle/ruby/1.9.1/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
vendor/bundle/ruby/1.9.1/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-4.2.3/lib/action_dispatch/middleware/static.rb:116:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `public_send'
vendor/bundle/ruby/1.9.1/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `method_missing'
thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.6.3) lib/thin/connection.rb:84:in `catch'
thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
thin (1.6.3) lib/thin/connection.rb:53:in `process'
thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
thin (1.6.3) lib/thin/server.rb:162:in `start'
thin (1.6.3) lib/thin/controllers/controller.rb:87:in `start'
thin (1.6.3) lib/thin/runner.rb:200:in `run_command'
thin (1.6.3) lib/thin/runner.rb:156:in `run!'
thin (1.6.3) bin/thin:6:in `<top (required)>'
/usr/local/bin/thin:23:in `load'
/usr/local/bin/thin:23:in `<main>'
```

**Comment by tomzx** [comment]
Verified @ f71a7f1f806dc2b1e1527c438ca93d28302c0107.
