### ISSUE TITLE
Couldn't find HOME environment -- expanding `~'  on first vagrant up/provision

### ISSUE THREAD

**Issue by tomzx** [eXolnet/redmine-code-audit#75]
```
/var/www/redmine/vendor/bundle/ruby/1.9.1/gems/yard-0.8.7.6/lib/yard.rb:11:in `expand_path': couldn't find HOME environment -- expanding `~' (ArgumentError)
        from /var/www/redmine/vendor/bundle/ruby/1.9.1/gems/yard-0.8.7.6/lib/yard.rb:11:in `<module:YARD>'
        from /var/www/redmine/vendor/bundle/ruby/1.9.1/gems/yard-0.8.7.6/lib/yard.rb:3:in `<top (required)>'
        from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
        from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
        from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
        from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
        from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
        from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
        from /var/www/redmine/config/application.rb:5:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/www/redmine/config/environment.rb:2:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/www/redmine/config.ru:3:in `block in <main>'
        from /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from /var/www/redmine/config.ru:1:in `new'
        from /var/www/redmine/config.ru:1:in `<main>'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `eval'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `load'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/rack/adapter/loader.rb:42:in `for'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/thin/controllers/controller.rb:170:in `load_adapter'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/thin/controllers/controller.rb:74:in `start'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/bin/thin:6:in `<top (required)>'
        from /usr/local/bin/thin:23:in `load'
        from /usr/local/bin/thin:23:in `<main>'
```

**Comment by tomzx** [comment]
A temporary fix is to run /etc/init.d/thin restart as root.
